In [2]:
import numpy as np

In [3]:
# List Vs Numpy Time Take

In [4]:
from time import process_time


In [5]:
# time taken list
pyhton_list=[i for i in range(10000000)]
# 0 1  2 3 4 5 6 7 8 9 ....
start_time=process_time()

pyhton_list=[i+5 for i in pyhton_list]
end_time=process_time()

print(end_time-start_time)

0.46875


In [6]:
# Numpy Array
np_array=np.array([i for i in range(10000000)])
start_time=process_time()

np_array +=5
end_time=process_time()
print(end_time-start_time)

0.015625


In [7]:
# List 
list1=[1,2,3,4,5,6,7,8]
print(list1)
type(list1)

[1, 2, 3, 4, 5, 6, 7, 8]


list

In [8]:
np_array=np.array([1,2,3,4,5,6,7,8])
print(np_array)
type(np_array)

[1 2 3 4 5 6 7 8]


numpy.ndarray

In [9]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [10]:
a.shape

(9,)

In [11]:
b=np.array([(1,2,3),(4,5,6)])
print(b)



[[1 2 3]
 [4 5 6]]


In [12]:
b.shape

(2, 3)

In [35]:
c=np.array([(1.6,2,3),(4,5,6),(7,8,9)],dtype=float)
print(c)

[[1.6 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [36]:
# Intail Placeholder
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [37]:
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# Create Array paticular functions
z=np.full((5,4),2)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [17]:
# Create Indentity Martix
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
# Create Numpy With Random Values
b=np.random.random((3,4))
print(b)

[[0.97172341 0.76227391 0.4336678  0.30891039]
 [0.49492977 0.43785936 0.38081643 0.371075  ]
 [0.24337076 0.89255181 0.10939067 0.77670179]]


In [19]:
# Random Value Array with in integer
c=np.random.randint(100000,100000000,(2,5))
print(c)

[[12570328 85370625  1693352 76198788 24329955]
 [64602633 12909590  6134298 37261869 89258008]]


In [20]:
# Arrays of evently space
d=np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [21]:
# Araray pf eventrly in specfic range
x=np.arange(10,30,5)
print(x)

[10 15 20 25]


In [22]:
# Convert list to array
list2=[1,2,3,4,5,6]
np_array=np.asarray(list2)
type(np_array)

numpy.ndarray

In [23]:
# Analysis a numpy array
c=np.random.randint(10,90,(5,5))
print(c)

[[27 50 89 71 52]
 [11 82 55 55 18]
 [77 38 86 84 52]
 [57 40 34 59 86]
 [82 30 50 56 35]]


In [24]:
print(c.shape)

(5, 5)


In [25]:
print(c.ndim)

2


In [26]:
print(c.size)

25


In [27]:
print(c.dtype)

int32


In [28]:
# Mathematical Operations for Nump

In [29]:
a=np.random.randint(10,50,(3,3))
b=np.random.randint(50,99,(3,3))
print(a)
print(b)
print(a+b)

[[35 34 28]
 [34 37 47]
 [39 38 49]]
[[74 53 85]
 [96 61 81]
 [68 67 53]]
[[109  87 113]
 [130  98 128]
 [107 105 102]]


In [30]:
print(np.add(a, b))

[[109  87 113]
 [130  98 128]
 [107 105 102]]


In [31]:
# Array Manipulation
a=np.random.randint(0,10,(2,3))
print(a)

[[0 7 4]
 [2 5 3]]


In [32]:
trans=np.transpose(a)
print(trans)

[[0 2]
 [7 5]
 [4 3]]
